/*------------------------------------------------------------------------------
;
;   Proton MKII MEGA DEMO for The Wellington Boot Loader
;
;   Copyright (c) 2014 - 2015 Darron M Broad
;
;------------------------------------------------------------------------------

;------------------------------------------------------------------------------
;   This file is part of The Wellington Boot Loader.
;
;   The Wellington Boot Loader is free software: you can redistribute it and/or
;   modify it under the terms of the GNU General Public License as published
;   by the Free Software Foundation.
;
;   The Wellington Boot Loader is distributed in the hope that it will be
;   useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
;   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
;   GNU General Public License for more details.
;
;   You should have received a copy of the GNU General Public License along
;   with The Wellington Boot Loader. If not, see http://www.gnu.org/licenses/
;-----------------------------------------------------------------------------*/

#ifndef _PROTON_MKII_H
#define _PROTON_MKII_H

#include <pic18fregs.h>

/*
 * WARNING: The target device seems to support XINST and no #pragma config XINST=OFF was found.
 *          The code generated by SDCC does probably not work when XINST is enabled (possibly by default).
 *          Please make sure to disable XINST.
 *          (If the target does not actually support XINST, please report this as a bug in SDCC.)
 */
#pragma config XINST=OFF

#pragma stack 0x0200 0x0100

/* Serial UART */
#define UART_SPEED (19200)			/* BAUDRATE */
#define UART_BRG ((((FOSC / UART_SPEED) / 2) - 1) / 2)

#define UART_STDIO (0)				/* printf to UART? */
#define UART_2STOP (0)				/* 2 stop bits?    */

#if UART_STDIO == 1
#include <stdio.h>
#include <stdlib.h>
#endif
#include <string.h>
#include <stdint.h>

/* Timing */
#define FOSC (40000000)				/* Oscillator frequency */
#define FCY  (FOSC / 4)				/* Instructions per second */

#define DELAY50U (FCY / 81967)			/* >50us delay for delay_tcy() */
#define DELAY10U (FCY / 454545)			/* >10us delay for delay_tcy() */

/* CAN Bus */
#define CAN_ID_ALL (0)				/* RX all messages, else   */
#define CAN_ID (0x699)		 		/* RX only this Message-Id */

#define CAN_SPEED (125)

#if CAN_SPEED == 50
#define CAN_BRG1 (0x18)				/* 50kbaud @ 40 MHz */
#define CAN_BRG2 (0xBC)
#define CAN_BRG3 (0x01)
#elif CAN_SPEED == 100
#define CAN_BRG1 (0x18)				/* 100kbaud @ 40 MHz */
#define CAN_BRG2 (0x84)
#define CAN_BRG3 (0x00)
#elif CAN_SPEED == 125
#define CAN_BRG1 (0x09)				/* 125kbaud @ 40 MHz */
#define CAN_BRG2 (0xBC)
#define CAN_BRG3 (0x01)
#elif CAN_SPEED == 250
#define CAN_BRG1 (0x04)				/* 250kbaud @ 40 MHz */
#define CAN_BRG2 (0xBC)
#define CAN_BRG3 (0x01)
#elif CAN_SPEED == 500
#define CAN_BRG1 (0x04)				/* 500kbaud @ 40 MHz */
#define CAN_BRG2 (0x84)
#define CAN_BRG3 (0x00)
#endif

#define CAN_LEN (8)				/* Message length */

#define CAN_WIN_TXB0 (0x08)			/* TX window */
#define CAN_WIN_TXB1 (0x06)
#define CAN_WIN_TXB2 (0x04)

#define CAN_WIN_RXB0 (0x00)			/* RX window */
#define CAN_WIN_RXB1 (0x0A)

#define CAN_RING_TX (3)				/* TX ring size */
#define CAN_RING_RX (2)				/* RX ring size */

#define CAN_DOUBLE_BUFFER_RX (1)		/* RXB0CON RB0DBEN */

#endif
