#include <stdio.h>
#include "srcp.h"

typedef struct {
   int ErrorCode;
   char *AnswerTemplate;
} AnswerStruct;

static AnswerStruct AnswerHandshakeTable[] = {
   { SRCP_ERRNO_ANTWORT_HANDSHAKE_GO_OK, SRCP_STR_ANTWORT_HANDSHAKE_GO_OK },
   { SRCP_ERRNO_ANTWORT_HANDSHAKE_PROTO_OK, SRCP_STR_ANTWORT_HANDSHAKE_PROTO_OK },
   { SRCP_ERRNO_ANTWORT_HANDSHAKE_CONMODE_OK, SRCP_STR_ANTWORT_HANDSHAKE_CONMODE_OK },
   { SRCP_ERRNO_ANTWORT_HANDSHAKE_PROTO_ERR, SRCP_STR_ANTWORT_HANDSHAKE_PROTO_ERR },
   { SRCP_ERRNO_ANTWORT_HANDSHAKE_CONMODE_ERR, SRCP_STR_ANTWORT_HANDSHAKE_CONMODE_ERR },
   { SRCP_ERRNO_ANTWORT_HANDSHAKE_INSUFFD_ERR, SRCP_STR_ANTWORT_HANDSHAKE_INSUFFD_ERR },
   { SRCP_ERRNO_ANTWORT_HANDSHAKE_NORES_ERR, SRCP_STR_ANTWORT_HANDSHAKE_NORES_ERR },
};


int SrcpEncAnswerHandshake(char *Buf, int Answer, char *Param)
{
   return(sprintf(Buf, AnswerHandshakeTable[Answer].AnswerTemplate, Param)+1);
}
