/*
RailControl - Model Railway Control Software

Copyright (c) 2017-2020 Dominik (Teddy) Mahrer - www.railcontrol.org

RailControl is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 3, or (at your option) any
later version.

RailControl is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with RailControl; see the file LICENCE. If not see
<http://www.gnu.org/licenses/>.
*/

#include "Languages.h"
#include "Utils/Utils.h"








const char* Languages::languages[MaxTexts][MaxLanguages] =
{
/* Text180Deg */ { "180 degrees", "180 Grad", "180 grados" },
/* Text90DegAntiClockwise */ { "90 degrees anti-clockwise", "90 Grad gegen den Uhrzeigersinn", "90 grados en el sentido contrario de las agujas del reloj" },
/* Text90DegClockwise */ { "90 degrees clockwise", "90 Grad im Uhrzeigersinn", "90 grados en el sentido de las agujas del reloj" },
/* TextAccessories */ { "Accessories", "Zubehörartikel", "Accesorios" },
/* TextAccessory*/ { "accessory", "Zubehörartikel", "accesorio" },
/* TextAccessoryAddressDccTooHigh */ { "Addresses higher then 2044 are not supported by DCC", "Adressen grösser als 2044 werden nicht unterstützt von DCC", "Direcciones más grandes que 2044 no están compatibles con DCC" },
/* TextAccessoryAddressMmTooHigh */ { "Addresses higher then 320 are not supported by MM1/MM2", "Adressen grösser als 320 werden nicht unterstützt von MM1/MM2", "Direcciones más grandes que 320 no están compatibles con MM1/MM2" },
/* TextAccessoryDeleted */ { "Accessory {0} deleted", "Zubehörartikel {0} gelöscht", "Accessorio {0} eliminado" },
/* TextAccessoryDoesNotExist */ { "Acessory does not exist", "Zubehörartikel existiert nicht", "Accesorio no existe" },
/* TextAccessoryIsLocked */ { "Accessory {0} is locked", "Zubehörartikel {0} ist gesperrt", "Accesorio {0} está bloqueado" },
/* TextAccessorySaved */ { "Accessory {0} saved", "Zubehörartikel {0} gespeichert", "Accesorio {0} guardado" },
/* TextAccessorySenderThreadStarted */ { "Accessory sender thread started", "Zubehörartikel Sender Thread gestartet", "Thread enviador accesorio creado" },
/* TextAccessoryStateIsGreen */ { "Accessory state of {0} is now green", "Der Status des Zubehörartikels ist nun grün", "El estado del accessorio está verde" },
/* TextAccessoryStateIsRed */ { "Accessory state of {0} is now red", "Der Status des Zubehörartikels ist nun rot", "El estado del accessorio está rojo" },
/* TextAccessoryUpdated */ { "Accessory {0} updated", "Zubehörartikel {0} aktualisiert", "Accessorio {0} actualizado" },
/* TextActualAndStoredProtocolsDiffer */ { "Actual ({0}) and stored ({1}) protocols differ", "Aktuelles ({0}) und gespeichertes ({1}) Protokoll unterscheiden sich", "protocolo reciente y guardado son diferentes" },
/* TextAddAccessory */ { "Add accessory", "Zubehörartikel hinzufügen", "Añadir accesorio" },
/* TextAddFeedback */ { "Add feedback", "Rückmelder hinzufügen", "Añadir retroseñal" },
/* TextAddSignal */ { "Add signal", "Signal hinzufügen", "Añadir señal" },
/* TextAddStreet */ { "Add street", "Fahrstrasse hinzufügen", "Añadir itinerario" },
/* TextAddSwitch */ { "Add switch", "Weiche hinzufügen", "Añadir desvío" },
/* TextAddTrack */ { "Add track", "Gleis hinzufügen", "Añadir vía" },
/* TextAddingFeedback */ { "Adding feedback {0}", "Rückmelder {0} hinzugefügt", "Retroseñal añadido" },
/* TextAddress */ { "Address", "Adresse", "Dirección" },
/* TextAddressMustBeHigherThen0 */ { "Address must be higher then 0", "Adresse muss grösser sein als 0", "Dirección tiene que ser mas que 0" },
/* TextAllTrains */ { "all trains", "alle Züge", "todos los trenes" },
/* TextAllowedTrains */ { "Allowed trains:", "Erlaubte Züge", "Trenes permitidos" },
/* TextAreYouSureToDelete */ { "Are you sure you really want to delete {0}?", "Sind sie sicher, dass sie {0} löschen möchten?", "Está usted seguro, que usted quiere eliminar {0}?" },
/* TextAtLock */ { "At lock", "Beim Sperren", "Durante bloquear" },
/* TextAtUnlock */ { "At unlock", "Beim Freigeben", "Durante liberar" },
/* TextAutomaticallyAddUnknownFeedbacks */ { "Automatically add unknown feedbacks", "Füge unbekannte Rückmelder automatisch hinzu", "Añadir retroseñales desconosidos automaticamente" },
/* TextAutomode */ { "Automode", "Automode", "Autómodo" },
/* TextBasic */ { "Basic data", "Basisdaten", "Datos basicos" },
/* TextBlockTrack */ { "Block track", "Blockiere Gleis", "Bloquear vía" },
/* TextBoosterIsTurnedOff */ { "Booster is turned off", "Booster ist ausgeschaltet", "Booster está apagado" },
/* TextBoosterIsTurnedOn */ { "Booster is turned on", "Booster ist eingeschaltet", "Booster está encendido" },
/* TextBridge */ { "Bridge", "Brücke", "Puente" },
/* TextBufferStop */ { "End / Buffer Stop", "Ende / Prellbock", "Final / Tope" },
/* TextCV */ { "CV", "CV", "CV" },
/* TextCanNotOpenLibrary */ { "Can not open library {0}: {1}", "Kann Bibliothek {0} nicht öffenen: {1}", "Imposible abrir biblioteca {0}: {1}" },
/* TextCanNotStartAlreadyRunning */ { "Can not start {0} because it is already running", "Unmöglich {0} zu starten weil schon gestartet", "Imposible poner {0} en marcha porque ya está en marcha" },
/* TextCanNotStartInErrorState */ { "Can not start {0} because it is in error state", "Unmöglich {0} zu startein weil sie im Fehlerstatus ist", "Imposible poner {0} en marcha perque está en estado error" },
/* TextCanNotStartNotOnTrack */ { "Can not start {0} because it is not on a track", "Unmöglich {0} zu starten weil sie nicht auf einem Gleis ist", "Imposible poner {0} en marcha porque no está sobre un vía" },
/* TextCheckSumError */ { "Checksum error", "Checksummen fehler", "Error de checksum" },
/* TextClosingSQLite */ { "Closing SQLite database", "Schliesse SQLite Datenbank", "Cerrando base de datos SQLite" },
/* TextConnectionFailed */ { "Connection to {0}:{1} failed", "Verbindung zu {0}:{1} nicht möglich", "Imposible conectar a {0}:{1}" },
/* TextConnectionRefused */ { "Connection to {0}:{1} refused", "Verbindung zu {0}:{1} zurückgewiesen", "Falló intento de conectar a {0}:{1}" },
/* TextConnectionReset */ { "Connection reset", "Verbindung zurückgesetzt", "Conexión reajustado" },
/* TextControl */ { "Control", "Zentrale", "Control" },
/* TextControlDeleted */ { "Control {0} deleted", "Zentrale {0} gelöscht", "Control {0} eliminado" },
/* TextControlDoesNotAnswer */ { "Control does not answer", "Zentrale antwortet nicht", "Control no respuesta" },
/* TextControlDoesNotExist */ { "Control does not exist", "Zentrale existiert nicht", "Control no existe" },
/* TextControlReturnedBadParameter */ { "Control returned bad parameter", "Zentrale sendete falscher Parameter", "Control respondió malo parametro" },
/* TextControlReturnedError */ { "Control returned error: {0}", "Zentrale meldete Fehler: {0}", "Control contesta error: {0}" },
/* TextControlReturnedOnHalt */ { "Control returned on HALT", "Zentrale sendete auf HALT", "Control respondió en HALT" },
/* TextControlReturnedPowerOff */ { "Control returned Power Off", "Zentrale sendete Strom aus", "Control respondió codico booster apagado" },
/* TextControlReturnedQueueFull */ { "Control returned queue full", "Zentrale sendete Warteschlange voll", "Control respondió cola lleno" },
/* TextControlReturnedQueueNearlyFull */ { "Control returned queue nearly full", "Zentrale sendete Warteschlange fast voll", "Control respondió cola casi lleno" },
/* TextControlReturnedUnknownErrorCode */ { "Control returned unknown error code: {0}", "Zentrale sendete unbekannten Fehlercode: {0}", "Control respondió codico error disconocido: {0}" },
/* TextControlSaved */ { "Control {0} saved", "Zentrale {0} gespeichert", "Control {0} guardado" },
/* TextControls */ { "Controls", "Zentralen", "Controls" },
/* TextCopyingFromTo */ { "Copying from {0} to {1}", "Kopiere von {0} nach {1}", "Copiando de {0} a {1}" },
/* TextCreatingTable */ { "Creating table {0}", "Erstelle Tabelle {0}", "Creando table {0}" },
/* TextCreepAt */ { "Creep at", "Schleichgeschwindigkeit bei", "Velocidad a rastras a" },
/* TextCreepingSpeed */ { "Creeping speed", "Kriech Geschwindigkeit", "Velocidad a rastras" },
/* TextDcc */ { "DCC", "DCC", "DCC" },
/* TextDebounceThreadStarted */ { "Debounce thread started", "Entprellthread gestartet", "Antirebote thread encendido" },
/* TextDebounceThreadTerminated */ { "Debounce thread terminated", "Entprellthread beedet", "Antirebote thread apagado" },
/* TextDebouncer */ { "Debouncer", "Entpreller", "Antirebote" },
/* TextDebug */ { "debug", "Entkäfern", "depurar" },
/* TextDefaultSwitchingDuration */ { "Default switching duration (ms)", "Standard Schaltzeit (ms)", "Duración de conmutación por defecto (ms)" },
/* TextDelete */ { "Delete", "Löschen", "Eliminar" },
/* TextDeleteAccessory */ { "Delete accessory", "Zubehörartickel löschen", "Eliminar accesorio" },
/* TextDeleteControl */ { "Delete control", "Zentrale löschen", "Eliminar control" },
/* TextDeleteFeedback */ { "Delete feedback", "Rückmelder löschen", "Eliminar retroseñal" },
/* TextDeleteLayer */ { "Delete layer", "Schicht löschen", "Eliminar capa" },
/* TextDeleteLoco */ { "Delete locomotive", "Lokomotive löschen", "Eliminar locomotora" },
/* TextDeleteSignal */ { "Delete signal", "Signal löschen", "Eliminar señal" },
/* TextDeleteStreet */ { "Delete street", "Fahrstrasse löschen", "Eliminar itinerario" },
/* TextDeleteSwitch */ { "Delete switch", "Weiche löschen", "Eliminar desvío" },
/* TextDeleteTrack */ { "Delete track", "Gleis löschen", "Eliminar vía" },
/* TextDestinationSignalTrack */ { "Destination signal or track", "Zielsignal oder -gleis", "Señal o vía de destino" },
/* TextDifferentDirections */ { "Locomotive and street {0} have different running directions", "Lokomotive und Fahrstrasse {0} haben verschiedene Fahrtrichtungen", "Tren e itinerario tienen sentidos de la marcha differentes" },
/* TextDifferentPushpullTypes */ { "Locomotive and street {0} have different push-pull types", "Lokomotive und Fahrstrasse {0} haben verschiedene Wendezugeinstellungen", "Tren e itinerario tienen ajustes de push-pull differentes" },
/* TextDirect */ { "Direct", "Direkt", "Directo" },
/* TextDoNotCare */ { "Do not care", "Egal", "No importa" },
/* TextDroppingTable */ { "Dropping table {0}", "Lösche Tabelle {0}", "Eliminando tabla {0}" },
/* TextDuration */ { "Switching duration (ms)", "Schaltzeit (ms)", "Duración de conmutación (ms)" },
/* TextEdit */ { "Edit", "Bearbeiten", "Editar" },
/* TextEditAccessory */ { "Edit accessory", "Zubehörartickel bearbeiten", "Editar accesorio" },
/* TextEditFeedback */ { "Edit feedback", "Rückmelder bearbeiten", "Editar retroseñal" },
/* TextEditSignal */ { "Edit signal", "Signal bearbeiten", "Editar señal" },
/* TextEditStreet */ { "Edit street", "Fahrstrasse bearbeiten", "Editar itinerario" },
/* TextEditSwitch */ { "Edit switch", "Weiche bearbeiten", "Editar desvío" },
/* TextEditTrack */ { "Edit track", "Gleis bearbeiten", "Editar vía" },
/* TextEnglish */ { "English", "Englisch", "Ingles" },
/* TextError */ { "error", "Fehler", "errores" },
/* TextExecutingStreet */ { "Executing street {0}", "Führe Fahrstrasse {0} aus", "Ejecutando itinerario {0}" },
/* TextFeedback */ { "feedback", "Rückmelder", "retroseñal" },
/* TextFeedbackChange */ { "State of pin {0} on S88 module {1} is {2}", "Status von Pin {0} an S88 Modul {1} ist {2}", "Estado de contacto {0} del S88 módulo {1} está {2}" },
/* TextFeedbackDeleted */ { "Feedback {0} deleted", "Rückmelder {0} gelöscht", "Retroseñal {0} eliminado" },
/* TextFeedbackDoesNotExist */ { "Feedback does not exist", "Rückmelder existiert nicht", "Retroseñal no existe" },
/* TextFeedbackSaved */ { "Feedback {0} saved", "Rückmelder {0} gespeichert", "Retroseñal {0} guardado" },
/* TextFeedbackStateIsOff */ { "Feedback state of {0} is now off", "Der Status des Rückmelders {0} ist nun aus", "El estado de la retroseñal {0} está apagado" },
/* TextFeedbackStateIsOn */ { "Feedback state of {0} is now on", "Der Status des Rückmelders {0} ist nun ein", "El estado de la retroseñal {0} está encendido" },
/* TextFeedbackUpdated */ { "Feedback {0} updated", "Rückmelder {0} aktualisiert", "Retroseñal {0} actualizado" },
/* TextFeedbacks */ { "Feedbacks", "Rückmelder", "Retroseñales" },
/* TextFoundAccessoryInEcosDatabase */ { "Found accessory in ECoS database: Address: {0} Name: {1}/{2}/{3}", "Zubehörartikel in ECoS Datenbank gefunden: Adresse: {0} Name: {1}/{2}/{3}", "Encontrado un accessorio en la base de datos de ECoS: Dirección: {0} Nombre: {1}/{2}/{3}" },
/* TextFoundFeedbackModuleInEcosDatabase */ { "Found feedback module in ECoS database: ID: {0}", "Rückmeldemodule in ECoS Datenbank gefunden: ID: {0}", "Encontrado un modulo retroseñal en la base de datos de ECoS: ID: {0}" },
/* TextFoundLocoInEcosDatabase */ { "Found locomotive in ECoS database: Address: {0} Name: {1}", "Locomotive in ECoS Datenbank gefunden: Adresse: {0} Name: {1}", "Encontrado una locomotora en la base de datos de ECoS: Dirección: {0} Nombre: {1}" },
/* TextGerman */ { "German", "Deutsch", "Aleman" },
/* TextGreen */ { "green", "grün", "verde" },
/* TextHasAlreadyReservedStreet */ { "{0} has already reserved a street. Setting error state.", "{0} hat schon eine Fahrstrasse reserviert. Setze Fehlerstatus.", "{0} ya ha reservado un itinerario. Poniando estado error." },
/* TextHasNotReachedDestination */ { "{0} has not yet reached its destination. Going to manual mode when it reached its destination.", "{0} hat ihr Ziel noch nicht erreicht. Setze sie in Modus manuell wenn sie ihr Ziel erreicht hat", "{0} no ha llegado su destino. Poniando en modo manual cuando ha llegado su destino." },
/* TextHeadingToVia */ { "Heading to {0} via {1}", "Fahre via {1} nach {0}", "Circulando por {1} a {0}" },
/* TextHeadingToViaVia */ { "Heading to {0} via {1} and {2}", "Fahre via {1} und {2} nach {0}", "Circulando por {1} y {2} a {0}" },
/* TextHeartBeatThreadStarted */ { "Heartbeat thread started", "Heartbeat-Thread gestartet", "Thread heartbeat creado" },
/* TextHeightIs0 */ { "Height is zero", "Höhe ist null", "Altura está zero" },
/* TextHint */ { "Hint:", "Hinweis:", "Nota:" },
/* TextHintCcSchnitte */ { "Under Linux the virtual serial port is usually /dev/ttyUSB0.", "Unter Linux ist der erstellte virtuelle COM-Port üblicherweise /dev/ttyUSB0.", "Sobre Linux el puerto virtual normalmente es /dev/ttyUSB0." },
/* TextHintCs2Tcp */ { "If you have an outdated CS2 software one must use CS2 UDP.", "Wenn die CS2 software veraltet ist muss stattdessen CS2 UDP verwendet werden.", "Si la software de la CS2 no está reciente, se tiene que usar CS2 UDP." },
/* TextHintCs2Udp */ { "Try CS2 TCP (new protocol) first. Use the CS2 UDP only, if you have an outdated CS2 software version.<br>To connect to a Märklin Central Station 2, the firewall has to allow UDP-connections to the remote port 15731 and from the remote port 15730.<br>The CAN settings have to be &quot;broadcast&quot; and the IP of the RailControl server.", "Vorzugsweise wird das CS2 TCP Protokoll benutzt. CS2 UDP sollte nur verwendet werden, wenn die CS2 Software nicht mehr aktuell ist.<br>Um die Märklin Central Station 2 mit RailControl zu verbinden, muss die Firewall UDP-Verbindungen zum remote Port 15731, sowie UDP-Verbindungen zum lokalen Port 15730 zulassen.<br>Die CAN Einstellungen müssen auf &quot;broadcast&quot; und die IP auf die Adresse vom RailControl server gestellt werden.", "Está mejor utilzar CS2 TCP. Solamente use CS2 UDP si el software de CS2 no está reciente.<br>Para conectar a una Märklin Central Station 2, el cortafuegos tiene que permitir UDP-conexiones al puerto remoto 15731 y del puerto remote 15730.<br>Los ajustes CAN tienen que ser &quot;broadcast&quot; y la IP tiene que ser la direcctión del servidor RailControl." },
/* TextHintEcos */ { "", "", "" },
/* TextHintHsi88 */ { "One has to count the S88 modules as 8-bit modules. 16-bit modules count as two modules.", "Die S88 Module müssen als 8-Bit Module gezählt werden. 16-Bit Module zählen entsprechend als zwei Module.", "Se tiene que contar los modulo S88 como 8-bit modulos. Cada Modulo S88 con 16 bits vale como dos modulos." },
/* TextHintM6051 */ { "Locomotives that are selected by a Central Control/Control 80/80f can not be controlled by RailControl.<br>The Interface 6050/6051 does not forward very short feedbacks. It is not recommended to use the feedbacks of the Interface 6050/6051 for automatic train control.", "Lokomotiven die von einer Central Control/Control 80/80f ausgewählt sind können von RailControl nicht gesteuert werden.<br>Das Interface 6050/6051 verschluckt sehr kurzzeitige Rückmelder. Ein Automatikbetrieb mit den Rückmeldern des Interface 6050/6051 ist deshalb nicht zu empfehlen.", "RailControl no puede controlar Locomotoras que estan selectionado por un Central Control/Control 80/80f.<br>El Interface 6050/6051 no puede procesar retroseñales muy cortos. No es recomendada de utilisar los retroseñales del Interface 6050/6051 para modo automatico." },
/* TextHintOpenDcc */ { "Under Linux the virtual serial port is usually /dev/ttyUSB0.<br>The OpenDcc does not forward very short feedbacks. It is not recommended to use the feedbacks of the OpenDCC for automatic train control.", "Unter Linux ist der erstellte virtuelle COM-Port üblicherweise /dev/ttyUSB0.<br>Das Interface 6050/6051 verschluckt sehr kurzzeitige Rückmelder. Ein Automatikbetrieb mit den Rückmeldern des Interface 6050/6051 ist deshalb nicht zu empfehlen.", "Sobre Linux el puerto virtual normalmente es /dev/ttyUSB0.<br>El OpenDCC no puede procesar retroseñales muy cortos. No es recomendada de utilisar los retroseñales del OpenDCC para modo automatico." },
/* TextHintRM485 */ { "This is a never published hardware of the main developer.", "Dies ist eine nie publizierte Hardware des Hauptentwicklers.", "Es un hardware que nunca fue publicado." },
/* TextHintVirtual */ { "The virtual control does not have a physical representation. It is for testing only.", "Die virtuelle Zentrale hat keine physische Repräsentation. Sie ist ausschliesslich für Tests.", "El control virtual no tiene representation physica. Es solamente para tests." },
/* TextHintZ21 */ { "To connect to a Z21, the firewall has to allow UDP-connections from and to the remote port 21105.", "Um die Z21 mit RailControl zu verbinden, muss die Firewall UDP-Verbindungen von und zum remote Port 21105 zulassen.", "Para conectar a un Z21, el cortafuegos tiene que permitir UDP-conexiones del y al puerto remoto 21105." },
/* TextHitOverrun */ { "{0} hit overrun feedback {1}", "{0} erreichte Überfahr-Rückmelder {1}", "{0} ha pasado a {1}" },
/* TextHsi88Configured */ { "{0} ({1}/{2}/{3}) S88 modules configured.", "{0} ({1}/{2}/{3}) S88 Module konfiguriert", "{0} ({1}/{2}/{3}) S88 módulos configurado" },
/* TextHsi88ErrorConfiguring */ { "Unable to configure HSI-88. HSI-88 returned {0} configured modules", "HSI-88 kann nicht konfiguriert werden. HSI-88 meldet {0} module", "Imposible configurar HSI-88. HSI-88 denuncia {0} módulos" },
/* TextHttpConnectionClose */ { "HTTP connection {0}: close", "HTTP Verbindung {0}: geschlossen", "HTTP connectión {0}: cerrado" },
/* TextHttpConnectionNotFound */ { "HTTP connection {0}: 404 Not found: {1}", "HTTP Verbindung {0}: Nicht gefunden: {1}", "HTTP connectión {0}: no encontrado" },
/* TextHttpConnectionNotImplemented */ { "HTTP connection {0}: HTTP method {1} not implemented", "HTTP Verbindung {0}: Methode {1} nicht implementiert", "HTTP connectión {0}: no implementado" },
/* TextHttpConnectionOpen */ { "HTTP connection {0}: open", "HTTP Verbindung {0}: geöffnet", "HTTP connectión {0}: abierto" },
/* TextHttpConnectionRequest */ { "HTTP connection {0}: Request: {1} {2}", "HTTP Verbindung {0}: Anfrage {1} {2}", "HTTP connectión {0}: solicitud: {1} {2}" },
/* TextIPAddress */ { "IP address", "IP Adresse", "Dirección IP" },
/* TextInfo */ { "info", "Informationen", "informaciones" },
/* TextInvalidControlID */ { "Invalid controlID {0}", "Ungültige Control ID {0}", "Control ID {0} no valido" },
/* TextInvalidDataReceived */ { "Invalid data received", "Ungültige Daten empfangen", "Recibido datos no validos" },
/* TextInverted */ { "Inverted", "Invertiert", "Invertido" },
/* TextIsInAutomodeWithoutStreetTrack */ { "{0} is in automode without a street or track set. Setting error state.", "{0} ist im Automodus ohne Fahrstrasse oder Gleis. Setze Fehlerstatus.", "{0} está en modo auto sin itinerario o vía. Poniando estado error." },
/* TextIsInErrorState */ { "{0} is in error state", "{0} ist im Fehlerstatus", "{0} está en estado error" },
/* TextIsInInvalidAutomodeState */ { "{0} is running in invalid automode state {1} while {2} is reached. Setting error state.", "{0} ist in unerlaubten Automode Status {1} während {2} erreicht wurde. Setze Fehlerstatus.", "{0} está en estado ilegal {1} mientras llegando {2}. Poniando estado error." },
/* TextIsInManualState */ { "{0} is in manual state while automode is running. Setting error state.", "{0} ist im Status manuell während der Auto-Modus eingeschaltet ist. Setze Fehlerstatus.", "{0} está en estado manual durante modo auto. Poniando estado error." },
/* TextIsInTerminatedState */ { "{0} is in terminated state while automode is running. Setting error state.", "{0} ist im Status beendet während der Auto-Modus eingeschaltet ist. Setze Fehlerstatus.", "{0} está en estado terminado durante modo auto. Poniando estado error." },
/* TextIsLocked */ { "{0} is locked", "{0} ist gesperrt", "{0} está bloqueado" },
/* TextIsNotFree */ { "{0} is not free", "{0} ist nicht frei", "{0} no está libre" },
/* TextIsNotOnTrack */ { "{0} is not on a track. Switching to manual mode.", "{0} ist nicht auf einem Gleis. Wechsle in den Modus manuell.", "{0} no está sobre una vía. Poniando en modo manual." },
/* TextIsNowInAutoMode */ { "{0} is now in automode", "{0} ist jetzt im Auto-Modus", "{0} está en modo auto" },
/* TextIsNowInManualMode */ { "{0} is now in manual mode", "{0} ist nun im Modus manuell", "{0} está en modo manual" },
/* TextIsOnOcupiedTrack */ { "{0} thinks it is on track {1} but there is {2}. Setting error state.", "{0} meint sie sei auf Gleis {1} aber dort ist {2}. Setze Fehlerstatus.", "{0} cree que está sobre vía {1} pero allá está {2}. Poniando estado error." },
/* TextIsRunningWaitingUntilDestination */ { "{0} is actually running, waiting until reached its destination", "{0} fährt noch, warte bis sie das Ziel erreicht hat.", "{0} todavía está en marcha, esperando hasta ha llegado el destino" },
/* TextIsUpToDate */ { "{0} is up to date", "{0} ist aktuell", "{0} es actual" },
/* TextLanguage */ { "Language", "Sprache", "Lingua" },
/* TextLayer1 */ { "Layer 1", "Schicht 1", "Capa 1" },
/* TextLayer1IsUndeletable */ { "Layer 1 is undeletable", "Schicht 1 ist unlöschbar", "Capa 1 no se puede eliminar" },
/* TextLayerDeleted */ { "Layer {0} deleted", "Schicht {0} gelöscht", "Capa {0} eliminado" },
/* TextLayerDoesNotExist */ { "Layer does not exist", "Schicht existiert nicht", "Capa no existe" },
/* TextLayerSaved */ { "Layer {0} saved", "Schicht {0} gespeichert", "Capa {0} guardado" },
/* TextLayerUpdated */ { "Layer {0} updated", "Schicht {0} aktualisiert", "Capa {0} actualizado" },
/* TextLayers */ { "Layers", "Schichten", "Capas" },
/* TextLeft */ { "left", "links", "izquierda" },
/* TextLength */ { "Length", "Länge", "Longitud" },
/* TextLibraryLoaded */ { "Library {0} loaded", "Bibliothek {0} geladen", "Biblioteca {0} carcando" },
/* TextLibraryUnloaded */ { "Library {0} unloaded", "Bibliothek {0} entladen", "Biblioteca {0} descarcado" },
/* TextLink */ { "Link", "Link", "Enlace" },
/* TextLoadedAccessory */ { "Loaded accessory {0}: {1}", "Zubehörartikel {0} geladen: {1}", "Cargado accesorio {0}: {1}" },
/* TextLoadedControl */ { "Loaded control {0}: {1}", "Zentrale {0} geladen: {1}", "Cargado control {0}: {1}" },
/* TextLoadedFeedback */ { "Loaded feedback {0}: {1}", "Rückmelder {0} geladen: {1}", "Cargado retroseñal {0}: {1}" },
/* TextLoadedLayer */ { "Loaded layer {0}: {1}", "Schicht {0} geladen: {1}", "Cargado capa {0}: {1}" },
/* TextLoadedLoco */ { "Loaded locomotive {0}: {1}", "Lokomotive {0} geladen: {1}", "Cargado locomotora {0}: {1}" },
/* TextLoadedSignal */ { "Loaded signal {0}: {1}", "Signal {0} geladen: {1}", "Cargado señal {0}: {1}" },
/* TextLoadedStreet */ { "Loaded street {0}: {1}", "Fahrstrasse {0} geladen: {1}", "Cargado itinerario {0}: {1}" },
/* TextLoadedSwitch */ { "Loaded switch {0}: {1}", "Weiche {0} geladen: {1}", "Cargado desvío {0}: {1}" },
/* TextLoadedTrack */ { "Loaded track {0}: {1}", "Gleis {0} geladen: {1}", "Cargado vía {0}: {1}" },
/* TextLoco */ { "Locomotive", "Lokomotive", "Locomotora" },
/* TextLocoAddressDccTooHigh */ { "Addresses higher then 10239 are not supported by DCC", "Adressen grösser als 10239 werden nicht unterstützt von DCC", "Direcciones más grandes que 10239 no están compatibles con DCC" },
/* TextLocoAddressMmTooHigh */ { "Addresses higher then 80 are not supported by MM1/MM2", "Adressen grösser als 80 werden nicht unterstützt von MM1/MM2", "Direcciones más grandes que 80 no están compatibles con MM1/MM2" },
/* TextLocoDeleted */ { "Locomotive {0} deleted", "Lokomotive {0} gelöscht", "Locomotora {0} eliminado" },
/* TextLocoDirectionIsLeft */ { "Direction of {0} is now left", "Die Fahrtrichtung von {0} ist links", "La dirección de {0} está izquierda" },
/* TextLocoDirectionIsRight */ { "Direction of {0} is now right", "Die Fahrtrichtung von {0} ist rechts", "La dirección de {0} está derecha" },
/* TextLocoDoesNotExist */ { "Locomotive does not exist", "Lokomotive existiert nicht", "Locomotora no existe" },
/* TextLocoEventDetected */ { "Locomotive event detected (ignored)", "Lokomotivevent erkannt (wird ignoriert)", "Evento de locomotora detectado (ignorando)" },
/* TextLocoFunctionIsOff */ { "F{1} of {0} is now off", "F{1} von {0} ist aus", "F{1} de {0} está apagado" },
/* TextLocoFunctionIsOn */ { "F{1} of {0} is now on", "F{1} von {0} ist an", "F{1} de {0} está encendido" },
/* TextLocoHasReachedDestination */ { "{0} has reached destination track {1} via {2}", "{0} hat das Zielgleis {1} über {2} erreicht.", "{0} ha llegado a su vía destino {1} vía {2}" },
/* TextLocoIsInAutoMode */ { "{0} is in auto mode", "{0} ist im Automatik-Betrieb", "{0} está en el modo automático" },
/* TextLocoIsInManualMode */ { "{0} is in manual mode", "{0} ist im manuellen Betrieb", "{0} está en el modo manual" },
/* TextLocoIsOnTrack */ { "{0} is on track {1}", "{0} ist auf Gleis {1}", "{0} está sobre vía {1}" } ,
/* TextLocoIsReleased */ { "{0} is released", " {0} ist freigegeben", "{0} está desbloqueada" },
/* TextLocoSaved */ { "Locomotive {0} saved", "Lokomotive {0} gespeichert", "Locomotora {0} guardado" },
/* TextLocoSpeedIs */ { "Speed of {0} is now {1}", "Die Geschwindigkeit von {0} ist {1}", "La velocidad de {0} está {1}" },
/* TextLocoUpdated */ { "Locomotive {0} updated", "Lokomotive {0} aktualisiert", "Locomotora {0} actualizado" },
/* TextLocos */ { "Locos", "Lokomotiven", "Locomotoras" },
/* TextLogLevel */ { "Log level", "Log Level", "Nivel de registro" },
/* TextLongestUnused */ { "Longest unused", "Am längsten ungenutzt", "El más largo sin usar" },
/* TextLookingForDestination */ {"Looking for new destination starting from {0}", "Suche von {0} aus neues Ziel", "Buscando nuevo destino deste {0}" },
/* TextMaerklinMotorola */ { "Märklin Motorola", "Märklin Motorola", "Märklin Motorola" },
/* TextManager */ { "Manager", "Manager", "Manager" },
/* TextMaxSpeed */ { "Maximum speed", "Maximale Geschwindigkeit", "Velocidad máxima" },
/* TextMaxTrainLength */ { "Maximal train length", "Maximale Zuglänge", "Longitud de tren maxima" },
/* TextMembers */ { "Members", "Teilnehmer", "Miembros" },
/* TextMinTrackLength */ { "Minimal track length", "Kürzestes Gleis", "Vía más corta" },
/* TextMinTrainLength */ { "Minimal train length", "Minimale Zuglänge", "Longitud de tren minima" },
/* TextMultipleUnit */ { "Multiple unit", "Mehrfachtraktion", "Unidad múltiple" },
/* TextName */ { "Name", "Name", "Nombre" },
/* TextNetworkUnreachable */ { "Network of {0}:{1} unreachable", "Netzwerk von {0}:{1} nicht erreichbar", "Red de {0}:{1} inaccesible" },
/* TextNew */ { "New", "Neu", "Nuevo" },
/* TextNoAnswerFromDecoder */ { "No answer from decoder", "Keine Antwort vom Decoder", "Ninguna respuesta del decoder" },
/* TextNoPushPull */ { "no push-pull trains", "keine Wendezüge", "ningunos push-pull trenes" },
/* TextNoRotation */ { "No rotation", "Keine Drehung", "Ninguna rotación" },
/* TextNoS88Modules */ { "No S88 modules configured", "Keine S88 Module konfiguriert", "No hay módulos S88 configurado" },
/* TextNoValidStreetFound */ { "No valid street found for {0}", "Keine Fahrstrasse gefunden für {0}", "Ningun itinerario encontrado para {0}" },
/* TextNotImplemented */ { "Not implemented at {0}:{1}", "Nicht implementiert bei {0}:{1}", "No implementado a {0}:{1}" },
/* TextNrOfFunctions */ { "Number of functions", "Anzahl der Funktionen", "Número de funciones" },
/* TextNrOfS88Modules */ { "# of S88 Modules (8 port)", "Anzahl S88 Module (8 Pin)", "Número de módulos S88 (8 contactos)" },
/* TextNrOfS88ModulesConfigured */ { "{0} S88 Modules (8 port)", "{0} S88 Module (8 Pin)", "{0} módulos S88 (8 contactos)" },
/* TextNrOfS88ModulesOnBus */ { "{0} S88 Modules (8 port) on bus {1}", "{0} S88 Module (8 Pin) an Bus {1}", "{0} módulos S88 (8 contactos) en bus {1}" },
/* TextNrOfTracksToReserve */ { "# of Tracks to reserve", "Anzahl der zu reservierenden Gleise", "Reservar numero de vías" },
/* TextOff */ { "off", "aus", "apagado" },
/* TextOn */ { "on", "ein", "encendido" },
/* TextOpeningSQLite */ { "Opening SQLite database with filename {0}", "Öffne SQLite Datenbank mit Dateiname {0}", "Abriendo base de datos SQLite con nombre {0}" },
/* TextOverrunAt */ { "Overrun at", "Überfahrt bei", "Pasar a" },
/* TextParameterFoundInConfigFile */ { "Parameter found in config file: {0} = {1}", "Parameter gefunden in Konfigurationsdate: {0} = {1}", "Parametro encontrado en fila de configuración: {0} = {1}" },
/* TextPin */ { "Pin", "Anschluss", "Contacto" },
/* TextPosX */ { "Position X", "Position X", "Posición X" },
/* TextPosY */ { "Position Y", "Position Y", "Posición Y" },
/* TextPosZ */ { "Layer", "Schicht", "Capa" },
/* TextPosition */ { "Position", "Position", "Posición" },
/* TextPositionAlreadyInUse */ { "Position {0}/{1}/{2} is already used by {3} \"{4}\".", "Position {0}/{1}/{2} wird bereits verwendet von {3} \"{4}\".", "Positión {0}/{1}/{2} está usado de {3} \"{4}\"." },
/* TextProgramDccPomAccessoryRead */ { "Reading DCC CV {1} of accessory with address {0} on main", "Lese DCC CV {1} des Zubehörartikels mit Adresse {0} auf dem Hauptgleis", "Leyendo DCC CV {1} del acessorio con dirección {0} en vía principal" },
/* TextProgramDccPomAccessoryWrite */ { "Programming DCC CV {1} of accessory with address {0} on main to value {2}", "Programmiere DCC CV {1} auf Wert {2} des Zubehörartikels mit Adresse {0} auf dem Hauptgleis", "Escribiendo DCC CV {1} al valor {2} del acessorio con dirección {0} en vía principal" },
/* TextProgramDccPomLocoRead */ { "Reading DCC CV {1} of locomotive with address {0} on main", "Lese DCC CV {1} der Lokomotive mit Adresse {0} auf dem Hauptgleis", "Leyendo DCC CV {1} de la locomotora con dirección {0} en vía principal" },
/* TextProgramDccPomLocoWrite */ { "Programming DCC CV {1} to value {2} of locomotive with address {0} on main", "Programmiere DCC CV {1} auf Wert {2} der Lokomotive mit Adresse {0} auf dem Hauptgleis", "Escribiendo DCC CV {1} al valor {2} de la locomotora con dirección {0} en vía principal" },
/* TextProgramDccRead */ { "Reading DCC CV {0} on programming track", "Lese DCC CV {0} auf dem Programmiergleis", "Leyendo DCC CV {0} en la vía de programación" },
/* TextProgramDccWrite */ { "Programming DCC CV {0} to value {1} on programming track", "Programmiere DCC CV {0} auf Wert {1} auf dem Programmiergleis", "Programando DCC CV {0} al valor {1}" },
/* TextProgramMfxRead */ { "Reading mfx CV {1} of locomotive with address {0}", "Lese mfx CV {1} der Lokomotive mit Adresse {0}", "Leyendo mfx CV {0} de la locomotora con dirección {0}" },
/* TextProgramMfxWrite */ { "Writing mfx CV {1} to value {2} of locomotive with address {0}", "Schreibe mfx CV {1} auf Wert {2} der Lokomotive mit Adresse {0}", "Escribiendo mfx CV {0} al valor {2} de la locomotora con dirección {0}" },
/* TextProgramMm */ { "Programming Märklin Motorola variable {0} to value {1} on programming track", "Programmiere Märklin Motorola Variable {0} auf Wert {1} auf dem Programmiergleis", "Programando Märklin Motorol variable {0} al valor {1} en la vía de programación" },
/* TextProgramMmPom */ { "Programming Märklin Motorola variable {1} to value {2} of locomotive with address {0} on main", "Programmiere Märklin Motorola Variable {1} auf Wert {2} der Lokomotive mit Adresse {0} auf dem Hauptgleis", "Programando Märklin Motorol variable {1} al valor {2} de la locomotora con dirección {0} en vía principal" },
/* TextProgramMode */ { "Mode", "Modus", "Modo" },
/* TextProgramModeDccDirect */ { "DCC direct (program track, all decoders)", "DCC direkt (Programmiergleis, alle Decoder)", "DCC directo (vía de programación, todos los decoders)" },
/* TextProgramModeDccPomAccessory */ { "DCC POM accessory (main track)", "DCC POM Zubehörartikel (Hauptgleis)", "DCC POM accesorio (vía principal)" },
/* TextProgramModeDccPomLoco */ { "DCC POM locomotive (main track)", "DCC POM Lokomotive (Hauptgleis)", "DCC POM locomotora (vía principal)" },
/* TextProgramModeMfx */ { "Märklin mfx (program and main track)", "Märklin mfx (Programmier- und Hauptgleis)", "Märklin mfx (vía de programación y principal)" },
/* TextProgramModeMm */ { "Märklin Motorola (program track, all decoders)", "Märklin Motorola (Programmiergleis, alle Decoder)", "Märklin Motorola (vía de programación, todos los decoders)" },
/* TextProgramModeMmPom */ { "Märklin Motorola (main track)", "Märklin Motorola (Hauptgleis)", "Märklin Motorola (vía principal)" },
/* TextProgramReadValue */ { "CV {0} has value {1}", "CV {0} hat den Wert {1}", "CV {0} tiene valor {1}" },
/* TextProgrammer */ { "Programmer", "Programmierer", "Programador" },
/* TextProgrammingMode */ { "Programming mode", "Programmiermodus", "Modo programador" },
/* TextProtocol */ { "Protocol", "Protocol", "Protocolo" },
/* TextProtocolNotSupported */ { "Protocol {0} is not supported by control. Please use one of: {1}", "Protokoll {0} wird nicht unterstützt von der Zentrale. Verwende eines aus {1}", "Protocolo {0} no está compatible con ese control. Utilisa uno de {1}" },
/* TextPushPullOnly */ { "push-pull trains only", "nur Wendezüge", "solamente push-pull trenes" },
/* TextPushPullTrain */ { "Push-Pull train", "Wendezug", "Tren push-pull" },
/* TextQuery */ { "Query: {0} Rows affected {1}", "Abfrage: {0} Geänderte Datensätze: {1}", "Consulta: {0} Líneas afectados: {1}" },
/* TextRM485ModuleFound */ { "RM485 module {0} found", "RM485 Modul {0} gefunden", "Modulo RM485 {0} encontrado" },
/* TextRailControlStarted */ { "RailControl started", "RailControl wurde gestartet", "RailControl encendido" },
/* TextRandom */ { "Random", "Zufall", "Aleatorio" },
/* TextReachedItsDestination */ { "{0} reached its destination", "{0} erreichte ihr Ziel", "{0} llegó su destino" },
/* TextRead */ { "read", "lesen", "leer" },
/* TextReadingConfigFile */ { "Reading config file {0}", "Lese Konfigurationsdatei {0}", "Leyendo fila de configuración {0}" },
/* TextReceivedAccessoryCommand */ { "Received command for accessory {0}/{1}: {2}", "Zubehörartikelkommando empfangen {0}/{1}: {2}", "Recibido comando para accesorio {0}/{1}: {2}" },
/* TextReceivedDirectionCommand */ { "Received direction command for locomotive {0}/{1}: {2}", "Richtungskommando empfangen für Lokomotive {0}/{1}: {2}", "Recibido comando de direccion para locomotora {0}/{1}: {2}" },
/* TextReceivedFunctionCommand */ { "Received function command for locomotive {0}/{1} and function {2}: {3}", "Funktionskommando empfangen für Lokomotive {0}/{1} und Funktion {2}: {3}", "Recibido comando de funcciona para locomotora {0}/{1} y funcciona {2}: 3}" },
/* TextReceivedSignalKill */ { "Received a signal kill {0} times. Exiting without saving.", "Signal Kill {0} mal erhalten. Beende RailControl ohne zu speichern.", "Señal Kill recibido {0} veces. Apagando RailControl sin guardar." },
/* TextReceivedSpeedCommand */ { "Received speed command for locomotive {0}/{1}: {2}", "Geschwindigkeitskommando empfangen für Lokomotive {0}/{1}: {2}", "Recibido comando de velocidad para locomotora {0}/{1}: {2}" },
/* TextReceiverThreadStarted */ { "Receiver thread started", "Empfangs-Thread gestartet", "Thread recibiendo creado" },
/* TextRed */ { "red", "rot", "rojo" },
/* TextReducedSpeed */ { "Reduced speed", "Reduzierte Geschwindigkeit", "Velocidad reducido" },
/* TextReducedSpeedAt */ { "Reduce speed at", "Reduziere Geschwindigkeit bei", "Reducir velocidad a" },
/* TextRegister */ { "Register", "Register", "Registro" },
/* TextRelationTargetNotFound */ { "Relation target not found", "Ziel der Relation nicht gefunden", "Relación no encontrado" },
/* TextRelease */ { "Release", "Freigeben", "Liberar" },
/* TextReleaseAccessory */ { "Release accessory", "Zubehörartikel freigeben", "Liberar accesorio" },
/* TextReleaseLoco */ { "Release locomotive", "Lokomotive freigeben", "Liberar locomotora" },
/* TextReleaseSignal */ { "Release signal", "Signal freigeben", "Liberar señal" },
/* TextReleaseStreet */ { "Release street", "Fahrstrasse freigeben", "Liberar itinerario" },
/* TextReleaseSwitch */ { "Release switch", "Weiche freigeben", "Liberar desvío" },
/* TextReleaseTrack */ { "Release track", "Gleis freigeben", "Liberar vía" },
/* TextReleaseTrackAndLoco */ { "Release track and locomotive", "Gleis und Lokomotive freigeben", "Liberar vía y locomotora" },
/* TextReleaseWhenFree */ { "Release when free", "Freigeben wenn nicht besetzt", "Liberar si no está ocupado" },
/* TextRemoveBackupFile */ { "Removing backup file {0}", "Lösche Sicherungskopie {0}", "Eliminando copia de respaldo {0}" },
/* TextRenamingFromTo */ { "Renaming from {0} to {1}", "Benenne von {0} nach {1} um", "Renombrando de {0} a {1}" },
/* TextRestarting */ { "Restarting", "Neustart", "Reiniciando" },
/* TextRight */ { "right", "rechts", "derecha" },
/* TextRotation */ { "Rotation", "Drehung", "Rotación", },
/* TextSQLiteErrorQuery */ { "SQLite error: {0} Query: {1}", "SQLite Fehler: {0} Query: {1}", "Error de SQLite: {0} Query: {1}" },
/* TextSaving */ { "Saving {0}", "Speichere {0}", "Guardando {0}" },
/* TextSelectLocoForTrack */ {"Select locomotive for track {0}", "Wähle Lokomotive für Gleis {0}", "Selectione locomotora para vía {0}" },
/* TextSelectStreetBy */ { "Select street by", "Wähle die Fahrstrasse nach", "Selecctionar itinerario por" },
/* TextSenderSocketCreated */ {"Sender socket created", "Sender socket erstellt", "Socket para enviar datos creado" },
/* TextSerialNumberIs */ { "Serialnumber is {0}", "Seriennummer ist {0}", "Número de serie es {0}" },
/* TextSerialPort */ { "Serial port", "Serieller Anschluss", "Puerto serie" },
/* TextSetLoco */ { "Set locomotive", "Setze Lokomotive", "Poner locomotora sobre vía" },
/* TextSettingAccessory */ { "Setting accessory {0}/{1} to {2}", "Setze Zubehörartikel {0}/{1} auf {2}", "Ajusto accesorio {0}/{1} a {2}" },
/* TextSettingAccessoryWithProtocol */ { "Setting accessory {0}/{1}/{2} to {3}", "Setze Zubehörartikel {0}/{1}/{2} auf {3}", "Ajusto accesorio {0}/{1}/{2} a {3}" },
/* TextSettingDirection */ { "Changing locomotive {0} direction", "Wechsle die Richtung der Lokomotive {0}", "Cambio la direccion de la locomotora {0}" },
/* TextSettingDirectionWithProtocol */ { "Setting locomotive {0}/{1} to direction {2}", "Setze Lokomotive {0}/{1} in Richtung {2}", "Ajusto la direccion de la locomotora {0}/{1} a {2}" },
/* TextSettingFunction */ { "Setting function {0} of locomotive {1} to {2}", "Setze Funktion {0} der Lokomotive {1} auf {2}", "Ajusto la function {0} de la locomotora {1} a {2}" },
/* TextSettingFunctionWithProtocol */ { "Setting function {0} of locomotive {1}/{2} to {3}", "Setze Funktion {0} der Lokomotive {1}/{2} auf {3}", "Ajusto la function {0} de la locomotora {1}/{2} a {3}" },
/* TextSettingFunctions17_28 */ { "Setting functions 17-28 of locomotive {0} to {1} and {2}", "Setze Funktionen 17-28 der Lokomotive {0} auf {1} und {2}", "Ajusto las functionas 17-28 de la locomotora {0} a {1} y {2}" },
/* TextSettingFunctions1_8 */ { "Setting functions 1-8 of locomotive {0} to {1}", "Setze Funktionen 1-8 der Lokomotive {0} auf {2}", "Ajusto las functionas 1-8 de la locomotora {0} a {1}" },
/* TextSettingFunctions9_16 */ { "Setting functions 9-16 of locomotive {0} to {1}", "Setze Funktionen 9-16 der Lokomotive {0} auf {2}", "Ajusto las functionas 9-16 de la locomotora {0} a {1}" },
/* TextSettingSpeed */ { "Setting locomotive {0} to speed {1}", "Setze Lokomotive {0} auf Geschwindigkeit {1}", "Ajusto la velocidad de la locomotora {0} a {1}" },
/* TextSettingSpeedDirectionLight */ { "Setting locomotive {0} to speed {1} and direction {2} and light {3}", "Setze Geschwindigkeit {1}, Richtung {2} und Licht {3} der Lokomotive {0}", "Ajusto velocidad a {1}, direccion {2} y luz {3} de la locomotora {0}" },
/* TextSettingSpeedWithProtocol */ { "Setting locomotive {0}/{1} to speed {2}", "Setze Lokomotive {0}/{1} auf Geschwindigkeit {2}", "Ajusto la velocidad de la locomotora {0}/{1} a {2}" },
/* TextSettings */ { "Settings", "Einstellungen", "Opciones" },
/* TextSettingsSaved */ { "Settings saved", "Einstellungen gespeichert", "Opciones guardado" },
/* TextShortCircuit */ { "Short circuit", "Kurzschluss", "Cortocircuit" },
/* TextSignal*/ { "signal ", "Signal", "señal" },
/* TextSignalDeleted */ { "Signal {0} deleted", "Signal {0} gelöscht", "Señal {0} eliminado" },
/* TextSignalDoesNotExist */ { "Signal does not exist", "Signal existiert nicht", "Señal no existe" },
/* TextSignalIsLocked */ { "Signal {0} is locked", "Signal {0} ist gesperrt", "Señal {0} está bloqueado" },
/* TextSignalSaved */ { "Signal {0} saved", "Signale {0} gespeichert", "Señal {0} guardado" },
/* TextSignalStateIsGreen */ { "Signal {0} is green", "Signal {0} ist grün", "Señal {0} está verde" },
/* TextSignalStateIsRed */ { "Signal {0} is red", "Signal {0} ist rot", "Señal {0} está roja" },
/* TextSignalUpdated */ { "Signal {0} updated", "Signal {0} aktualisiert", "Señal {0} actualizado" },
/* TextSignals */ { "Signals", "Signale", "Señales" },
/* TextSimpleLeft */ { "simple left", "einfach links", "simple izquierda" },
/* TextSimpleRight */ { "simple right", "einfach rechts", "simple derecha" },
/* TextSpanish */ { "Spanisch", "Spanisch", "Español" },
/* TextSpeed */ { "Speed", "Geschwindigkeit", "Velocidad" },
/* TextStartLoco */ { "Start locomotive", "Starte Lokomotive", "Poner locomotora en marcha" },
/* TextStartSignalTrack */ { "Start signal or track", "Startsignal oder -gleis", "Señal o vía de inicio" },
/* TextStarting */ { "Starting {0}", "Starte {0}", "Encendiendo {0}" },
/* TextStopAt */ { "Stop at", "Anhalten bei", "Parar a" },
/* TextStopLoco */ { "Stop locomotive", "Stoppe Lokomotive", "Parar locomotora" },
/* TextStoppingRailControl */ { "Stopping RailControl", "Beende RailControl", "Apagando RailControl" },
/* TextStoppingRequestedBySignal */ { "Stopping RailControl requested by signal {0}", "Beenden von RailControl angefordert mit Signal {0}", "Apagar RailControl pedido con señal {0}" },
/* TextStoppingRequestedByWebClient */ { "Stopping RailControl requested by webclient", "Beenden von RailControl angefordert von Webclient", "Apagar RailControl pedido del webclient" },
/* TextStraight */ { "straight", "gerade", "recto" },
/* TextStreet*/ { "street", "Fahrstrasse", "itinerario" },
/* TextStreetDeleted */ { "Street {0} deleted", "Fahrstrasse {0} gelöscht", "Itinerario {0} eliminado" },
/* TextStreetDoesNotExist */ { "Street does not exist", "Fahrstrasse existiert nicht", "Itinerario no existe" },
/* TextStreetIsLocked */ { "Street {0} is locked", "Fahrstrasse {0} ist gesperrt", "Itinerario {0} está bloqueado" },
/* TextStreetIsReleased */ { "Street {0} is released", "Fahrstrasse {0} ist freigegeben", "Itinerario {0} está desbloqueado" },
/* TextStreetSaved */ { "Street {0} saved", "Fahrstrasse {0} gespeichert", "Itinerario {0} guardado" },
/* TextStreetUpdated */ { "Street {0} updated", "Fahrstrasse {0} aktualisiert", "Itinerario {0} actualizado" },
/* TextStreets */ { "Streets", "Fahrstrassen", "Itinerarios" },
/* TextSwitch*/ { "switch", "Weiche", "desvío" },
/* TextSwitchDeleted */ { "Switch {0} deleted", "Weiche {0} gelöscht", "Desvío {0} eliminado" },
/* TextSwitchDoesNotExist */ { "Switch does not exist", "Weiche existiert nicht", "Desvío no existe" },
/* TextSwitchEventDetected */ { "Switch event detected (ignored)", "Weichenevent erkannt (wird ignoriert)", "Evento de desvío detectado (ignorando)" },
/* TextSwitchIsLocked */ { "Switch {0} is locked", "Weiche {0} ist gesperrt", "Desvío {0} está bloqueado" },
/* TextSwitchSaved */ { "Switch {0} saved", "Weiche {0} gespeichert", "Desvío {0} guardado" },
/* TextSwitchStateIsStraight */ { "Switch {0} is straight", "Weiche {0} ist geradeaus", "Desvío {0} está directo" },
/* TextSwitchStateIsTurnout */ { "Switch {0} is turnout", "Weiche {0} ist ablenkend", "Desvío {0} está desviado" },
/* TextSwitchUpdated */ { "Switch {0} updated", "Weiche {0} aktualisiert", "Desvío {0} actualizado" },
/* TextSwitches */ { "Switches", "Weichen", "Desvíos" },
/* TextSystemDefault */ { "Sysem default", "Systemeinstellung", "Configuración del sistema" },
/* TextTerminatingAccessorySenderThread */ { "Terminating accessory sender thread", "Beende Zubehörartikel Sender Thread", "Apagando thread enviador accesorio" },
/* TextTerminatingHeartBeatThread */ { "Terminating heartbeat thread", "Beende Heartbeat-Thread", "Apagando thread heartbeat" },
/* TextTerminatingReceiverThread */ { "Terminating receiver thread", "Beende Empfangs-Thread", "Apagando thread recibiendo" },
/* TextTerminatingSenderSocket */ { "Terminating sender socket", "Beende Sende Socket", "Apagando socket enviando" },
/* TextTimestampAlreadySet */ { "Timestamp already set", "Zeit schon gesetzt", "Hora ya ajustado" },
/* TextTimestampNotSet */ { "Timestamp not set", "Zeit nicht gesetzt", "Hora no ajustado" },
/* TextTimestampSet */ { "Timestamp set", "Zeit gesetzt", "Hora ajustado" },
/* TextTooManyS88Modules */ { "Too many S88 modules configured: {0}. Max is {1}", "Zu viele S88 Module konfiguriert: {0}. Maximum ist {1}", "Demasiado módulos S88 configurado: {0}. El maximo es {1}" },
/* TextTrack*/ { "track", "Gleis", "vía" },
/* TextTrackDeleted */ { "Track {0} deleted", "Gleis {0} gelöscht", "Vía {0} eliminado" },
/* TextTrackDoesNotExist */ { "Track does not exist", "Gleis existiert nicht", "Vía no existe" },
/* TextTrackIsInUse */ { "{0} is in use", "{0} ist in Benutzung", "{0} está en uso" },
/* TextTrackSaved */ { "Track {0} saved", "Gleis {0} gespeichert", "Vía {0} guardado" },
/* TextTrackStatusIsBlocked */ { "{0} is blocked", "{0} ist blockiert", "{0} está bloqueado" },
/* TextTrackStatusIsBlockedAndOccupied */ { "{0} is blocked and occupied", "{0} ist blockiert und besetzt", "{0} está bloqueado y ocupado" },
/* TextTrackStatusIsBlockedAndReserved */ { "{0} is blocked and reserved by {1}", "{0} ist blockiert und reserviert von {1}", "{0} está bloqueado y reservado por {1}" },
/* TextTrackStatusIsFree */ { "{0} is free", "{0} ist frei", "{0} está libre" },
/* TextTrackStatusIsOccupied */ { "{0} is occupied", "{0} ist besetzt", "{0} está ocupada" },
/* TextTrackStatusIsReserved */ { "{0} is reserved by {1}", "{0} ist reserviert von {1}", "{0} está reservada por {1}" },
/* TextTrackUpdated */ { "Track {0} updated", "Gleis {0} aktualisiert", "{0} actualizado" },
/* TextTracks */ { "Tracks", "Gleise", "Vías" },
/* TextTrainIsToLong */ { "Train is to long for street {0}", "Zug ist zu lang für die Fahrstrasse {0}", "El tren es demasiado largo para el itinerario {0}" },
/* TextTrainIsToShort */ { "Train is to short for street {0}", "Zug ist zu kurz für die Fahrstrasse {0}", "El tren es demasiado corto para el itinerario {0}" },
/* TextTrainLenght */ { "Train length", "Zuglänge", "Longitud de tren" },
/* TextTravelSpeed */ { "Travel speed", "Reisegeschwindigkeit", "Velocidad de viaje" },
/* TextTunnelOneSide */ { "Tunnel (one side)", "Tunnel (eine Seite)", "Túnel (un lado)" },
/* TextTunnelTwoSides */ { "Tunnel (two sides)", "Tunnel (zwei Seiten)", "Túnel (dos lados)" },
/* TextTurn */ { "turn", "gebogen", "curvo" },
/* TextTurnDirectionOfTravelToLeft */ { "Turn direction of travel to left", "Drehe Fahrtrichtung nach links", "Gire la dirección del movimiento hacia la izquierda" },
/* TextTurnDirectionOfTravelToRight */ { "Turn direction of travel to right", "Drehe Fahrtrichtung nach rechts", "Gire la dirección del movimiento hacia la dereja" },
/* TextTurningBoosterOff */ { "Turning booster off", "Deaktiviere Booster", "Apagando booster" },
/* TextTurningBoosterOn */ { "Turning booster on", "Aktiviere Booster", "Encendiendo booster" },
/* TextTurnout */ { "turnout", "abzweigend", "desviando" },
/* TextType */ { "Type", "Typ", "Typo" },
/* TextUnabelToStoreLibraryAddress */ { "Unable to store library address for {0}", "Adresse der Biblikothek {0} kann nicht gespeichert werden", "Imposible guardar la dirección de la biblioteca {0}" },
/* TextUnableToAddAccessory */ { "Unable to add accessory", "Nicht möglich den Zubehörartikel hinzuzufügen ", "Imposible añadir el accesorio" },
/* TextUnableToAddControl */ { "Unable to add control", "Nicht möglich die Zentrale hinzuzufügen ", "Imposible añadir el control" },
/* TextUnableToAddFeedback */ { "Unable to add feedback", "Nicht möglich den Rückmelder hinzuzufügen ", "Imposible añadir la retroseñal" },
/* TextUnableToAddLayer */ { "Unable to add layer", "Nicht möglich die Schicht hinzuzufügen ", "Imposible añadir la capa" },
/* TextUnableToAddLayer1 */ { "Unable to add initial layer 1", "Nicht möglich die Schicht 1 hinzuzufügen", "Imposible añadir capa 1" },
/* TextUnableToAddLoco */ { "Unable to add locomotive", "Nicht möglich die Lokomotive hinzuzufügen", "Impsible ańadir la locomotora" },
/* TextUnableToAddLocoToTrack */ { "Unable to add locomotive {0} to track {1}", "Nicht möglich die Lokomotive {0} auf Gleis {1} zu setzen", "Impsible poner la locomotora sobre vía {1}" },
/* TextUnableToAddSignal */ { "Unable to add signal", "Nicht möglich das Signal hinzuzufügen ", "Imposible añadir la señal" },
/* TextUnableToAddStreet */ { "Unable to add street", "Nicht möglich die Fahrstrasse hinzuzufügen ", "Imposible añadir el itinerario" },
/* TextUnableToAddSwitch */ { "Unable to add switch", "Nicht möglich die Weiche hinzuzufügen ", "Imposible añadir el desvío" },
/* TextUnableToAddTrack */ { "Unable to add track", "Nicht möglich das Gleis hinzuzufügen ", "Imposible añadir la vía" },
/* TextUnableToBindSocketToPort */ { "Unable to bind connection to port {0}", "Binden der Verbindung an Port {0} fehlgeschlagen", "Imposible vincular la conexión al puerto {0}" },
/* TextUnableToBindUdpSocket */ { "Unable to bind UDP socket to address", "Nicht möglich den UDP socket an eine Adresse zu binden", "Imposible enlazar el UDP socket a la dirección" },
/* TextUnableToCalculatePosition */ { "Unable to calculate position", "Unmöglich die Position zu berechnen", "Imposible calcular la posición" },
/* TextUnableToCreateStorageHandler */ { "Unable to create storage handler", "Unmöglich den Speicher Handler zu erstellen", "Imposible crear manipulador de almacenamiento" },
/* TextUnableToCreateTcpSocket */ { "Unable to create TCP socket for {0}:{1}", "TCP Socket für {0}:{1} erstellen fehlgeschlagen", "Imposible crear socket TCP para {0}:{1}" },
/* TextUnableToCreateUdpSocket */ { "Unable to create UDP socket for {0}:{1}", "UDP Socket für {0}:{1} erstellen fehlgeschlagen", "Imposible crear socket UDP para {0}:{1}" },
/* TextUnableToCreateUdpSocketForReceivingData */ { "Unable to create UDP socket to receive data from control", "Nicht möglich ein UDP socket zu erstellen um Daten von der Zentrale zu empfangen", "Imposible crear UDP socket para recibir datos del control" },
/* TextUnableToCreateUdpSocketForSendingData */ { "Unable to create UDP socket to send data to control", "Nicht möglich ein UDP socket zu erstellen um Daten an die Zentrale zu senden", "Imposible crear UDP socket para enviar datos al control" },
/* TextUnableToFindSymbol */ { "Unable to find symbol {0}", "Symbol {0} nicht gefunden", "Imposible encontrar simbolo {0}" },
/* TextUnableToLock */ { "Unable to lock {0}", "Sperren von {0} nicht möglich", "Imposible bloquear {0}" },
/* TextUnableToOpenFile */ { "Unable to open file {0}", "Öffnen der Datei {0} nicht möglich", "Imposible abrir fila {0}" },
/* TextUnableToOpenSQLite */ { "Unable to load SQLite database: {0}", "Öffnen von SQLite Datenbank nicht möglich: {0}", "Imposible abrir base de datos SQLite: {0}" },
/* TextUnableToOpenSerial */ { "Unable to open serial {0}", "Serieller Anschluss {0} kann nicht geöffnet werden", "Imposible abrir conexión serial {0}" },
/* TextUnableToReceiveData */ { "Unable to receive data", "Daten empfangen nicht möglich", "Imposible recibir datos" },
/* TextUnableToReserve */ { "Unable to reserve {0}", "Reservieren von {0} nicht möglich", "Imposible reservar {0}" },
/* TextUnableToResolveAddress */ { "Unable to resolve address {0}", "Adresse {0} auflösen fehlgeschalgen", "Imposible resolver la dirección {0}" },
/* TextUnableToSendDataToControl */ { "Unable to send data to control", "Nicht möglich Daten an die Zentrale zu senden", "Imposible enviar datos al control" },
/* TextUnblockTrack */ { "Unblock track", "Deblockere Gleis", "Desbloquear vía" },
/* TextUnknownObjectType */ { "Unknown object type", "Unbekannter Objekttyp", "Typo de objecto desconocido" },
/* TextUnloadingControl */ { "Unloading control {0}: {1}", "Entlade Zentrale {0}: {1}", "Descargando control {0}: {1}" },
/* TextValue */ { "Value", "Wert", "Valor" },
/* TextVersion */ { "Version: {0}", "Version: {0}", "Versión: {0}" },
/* TextVisible */ { "Visible", "Sichtbar", "Visible" },
/* TextWaitAfterRelease */ { "Wait after release (s)", "Wartezeit nach Freigabe (s)", "Tiempo de espera despues liberar (s)" },
/* TextWaitingTimeBetweenMembers */ { "Waiting time between members (ms)", "Wartezeit zwischen Teilnehmern (ms)", "Tiempo de esprera entre los miembros (ms)" },
/* TextWaitingUntilHasStopped */ { "Waiting until {0} has stopped", "Warte bis {0} angehalten hat", "Esperando hasta {0} ha parado" },
/* TextWarning */ { "warning", "Warnungen", "advertencias" },
/* TextWebServerStarted */ { "Webserver started", "Webserver wurde gestartet", "Servidor web encendido" },
/* TextWebServerStopped */ { "Webserver stopped", "Webserver wurde beendet", "Servidor web apagado" },
/* TextWidthIs0 */ { "Width is zero", "Breite ist null", "Anchura está zero" },
/* TextWrite */ { "write", "schreiben", "escribir" },
/* TextZ21Black2012 */ { "black Z21, hardware 2012", "schwarzen Z21, Hardware 2012", "Z21 negro, hardware 2012" },
/* TextZ21Black2013 */ { "black Z21, hardware 2013", "schwarzen Z21, Hardware 2013", "Z21 negro, hardware 2013" },
/* TextZ21DoesNotUnderstand */ { "Z21 does not understand our command", "Z21 versteht unser Kommando nicht", "Z21 no ha endendido nuestro comando" },
/* TextZ21NotRestricted */ { "Z21 does not have any restrictions", "Z21 hat keine Restriktionen", "Z21 no tiene restricctiones" },
/* TextZ21RestrictionsUnknown */ { "Z21 restrictions unknown", "Z21 Restriktionen unbekannt", "Z21 restricctiones desconocido" },
/* TextZ21SmartRail2012 */ { "SmartRail", "SmartRail", "SmartRail" },
/* TextZ21Start2016 */ { "z21 start", "z21 start", "z21 start" },
/* TextZ21StartLocked */ { "Z21 start is locked. Impssible to use this Z21!", "Z21 start ist gesperrt. Unmöglich diese Z21 zu benutzen!", "Z21 start está limitado. Imposible usar este Z21!" },
/* TextZ21StartUnlocked */ { "Z21 start is unlocked", "Z21 start ist offen", "Z21 start está abierto" },
/* TextZ21Type */ { "Connected to a {0} with firmware version {1}", "Verbunden mit einer {0} mit Firmware version {1}", "Conectado a {0} con firmware versión {1}" },
/* TextZ21Unknown */ { "unknown Z21", "unbekannten Z21", "Z21 desconosido" },
/* TextZ21White2013 */ { "white z21", "weissen z21", "z21 blanco" },
// /* Text */ { "", "", "" },
};

Languages::Language Languages::defaultLanguage = Languages::EN;
