#!/bin/sh /etc/rc.common
# Copyright (C) 2017 OpenWrt.org

START=99

start() {
	# modprobe sun4i_can
	/usr/sbin/ip link set can0 up type can bitrate 250000 restart-ms 10
	## WLAN add 10 seconds
	# sleep 10

	[ -e /www/config/ ] && {
		# we don't care about existing PID
		rm -f /var/run/can2lan.pid
		# for WLAN
		# can2lan -m -c /www/config -b wlan0
		# for LAN
		can2lan -m -c /www/config -b br-lan
	}
}

stop() {
	killall can2lan
}
