#!/bin/sh

tar cf /tmp/update.tar /home/developer/src/mrsystem/www/uci.css
tar rf /tmp/update.tar /home/developer/src/mrsystem/www/sysconf/mrsystem.hlp
tar rf /tmp/update.tar /home/developer/src/mrsystem/www/sysconf/mrsystem.cfg
tar rf /tmp/update.tar /home/developer/src/mrsystem/www/sysconf/daemons.def
tar rf /tmp/update.tar /home/developer/src/mrsystem/www/sysconf/daemons.hlp
tar rf /tmp/update.tar /home/developer/src/mrsystem/www/sysconf/mrsystem.def
tar rf /tmp/update.tar /home/developer/src/mrsystem/www/sysconf/daemons.cfg
tar rf /tmp/update.tar /home/developer/src/mrsystem/www/uci.php
tar rf /tmp/update.tar /home/developer/src/mrsystem/www/valchanged.sh
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_slcan/Makefile
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_slcan/main.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/etc/init.d/mrsystem
chown developer /home/developer/src/mrsystem/client_gpios88/Makefile
chgrp developer /home/developer/src/mrsystem/client_gpios88/Makefile
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_gpios88/Makefile
chown developer /tmp/update.tar /home/developer/src/mrsystem/client_gpios88/Makefile
chgrp developer /tmp/update.tar /home/developer/src/mrsystem/client_gpios88/Makefile
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_gpios88/Makefile
chown developer /home/developer/src/mrsystem/client_gpios88/s88.patch
chgrp developer /home/developer/src/mrsystem/client_gpios88/s88.patch
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_gpios88/s88.patch
chmod developer /home/developer/src/mrsystem/client_gpios88/startmrgpios88
chgrp /home/developer/src/mrsystem/client_gpios88/startmrgpios88
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_gpios88/startmrgpios88
chmod developer /home/developer/src/mrsystem/client_gpios88
chgrp /home/developer/src/mrsystem/client_gpios88
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/mr_can/cane1b.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/mr_can/sendeth.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/mr_can/Makefile
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/mr_can/cand1b.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/mr_can/mr_can.h
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/mr_can/sendtoeth.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/mr_can/m_cs2ms2.h
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/config/config.h
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/config/cfg_sint.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/config/cfg_gint.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/config/cfg_sstr.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/config/cfg_cmdline.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/config/cfg_intern.h
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/config/cfg_gstr.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/config/cfg_init.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/mr_ipc/encode_can.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/mr_ipc/cmd_get_can_bootldr.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/mr_ipc/cmd_set_track_proto.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/mr_ipc/cmd_set_system_status_val.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/mr_ipc/Makefile
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/mr_ipc/mr_ipc.h
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/mr_ipc/cmd_get_system_status_val.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/mr_ipc/cmd_set_can_bootldr.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/libs/mr_ipc/decode_can.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_cc/Makefile
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_cc/main.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_ms24l/Makefile
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_ms24l/main.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_cs2sl/cs2sl.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_cs2sl/Makefile
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_cs2sl/main.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_zentrale/zentrale.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_zentrale/zentrale.h
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_zentrale/main.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_zentrale/canmember.h
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_zentrale/states.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/Makefile
tar rf /tmp/update.tar /home/developer/src/mrsystem/doku/konfig.htm
tar rf /tmp/update.tar /home/developer/src/mrsystem/doku/erata.htm
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_cs2eth/main.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_cs2eth/cs2eth.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_ms2/ms2.h
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_ms2/Makefile
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_ms2/main.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_ms2/ms2.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_log/main.c
tar rf /tmp/update.tar /home/developer/src/mrsystem/client_log/log.c
tar rf /tmp/update.tar /home/developer/src/railroad/can2udp/src/a20.h
tar rf /tmp/update.tar /home/developer/src/railroad/can2udp/src/s88udp-bpi.c
tar rf /tmp/update.tar /home/developer/src/railroad/can2udp/src/s88test-bpi.c
tar rf /tmp/update.tar /home/developer/src/railroad/can2udp/src/s88udp-bpi.h
tar rf /tmp/update.tar /home/developer/src/railroad/can2udp/src/a20.c
tar rf /tmp/update.tar /home/developer/src/railroad/.git
tar rf /tmp/update.tar /var/www/uci.css
tar rf /tmp/update.tar /var/www/sysconf/mrsystem.hlp
tar rf /tmp/update.tar /var/www/sysconf/mrsystem.def
tar rf /tmp/update.tar /var/www/uci.php
tar rf /tmp/update.tar /var/www/valchanged.sh
tar rf /tmp/update.tar /var/www/sysconf/daemons.hlp
tar rf /tmp/update.tar /var/www/sysconf/daemons.cfg
tar rf /tmp/update.tar /var/www/sysconf/daemons.def
tar rf /tmp/update.tar /etc/init.d/mrsystem
tar rf /tmp/update.tar /tmp/update.sh
gzip /tmp/update.tar
