#!/bin/sh

uci -q batch <<-EOT >/dev/null
  set uhttpd.ms1relay=uhttpd
  set uhttpd.ms1relay.listen_http=82
  set uhttpd.ms1relay.home="/www/ms1relay/html"
  set uhttpd.ms1relay.cgi_prefix="/cgi.bin"
  add_list uhttpd.ms1relay.interpreter=".pl=/usr/bin/perl"
  set uhttpd.ms1relay.index_page="ms1Display.pl"
  commit uhttpd
EOT

