#ifndef CS2_TYPES_H
#define CS2_TYPES_H


#define LOKOMOTIVE_CS2_DECODER_MM2_DIL8 0x01
#define LOKOMOTIVE_CS2_DECODER_MM2_PROG 0x02
#define LOKOMOTIVE_CS2_DECODER_MMM2_LOK 0x03
#define LOKOMOTIVE_CS2_DECODER_MFX      0x04
#define LOKOMOTIVE_CS2_DECODER_DCC      0x05

#define LOKOMOTIVE_CS2_DECODER_STRING_MM2_DIL8 "mm2_dil8"
#define LOKOMOTIVE_CS2_DECODER_STRING_MM2_PROG "mm2_prg"
#define LOKOMOTIVE_CS2_DECODER_STRING_MMM2_LOK "mmm2_lok"
#define LOKOMOTIVE_CS2_DECODER_STRING_MFX      "mfx"
#define LOKOMOTIVE_CS2_DECODER_STRING_DCC      "dcc"

#define LOKOMOTVIE_CS2_FUNKTION_LEER                      0
#define LOKOMOTVIE_CS2_FUNKTION_STIRNBELEUCHTUNG          1
#define LOKOMOTVIE_CS2_FUNKTION_INNENBELEUCHTUNG          2
#define LOKOMOTVIE_CS2_FUNKTION_RUECKLICHT                3
#define LOKOMOTVIE_CS2_FUNKTION_RUECKLICHT                4
#define LOKOMOTVIE_CS2_FUNKTION_GERAEUSCH                 5
#define LOKOMOTVIE_CS2_FUNKTION_PANTOGRAF                 6
#define LOKOMOTVIE_CS2_FUNKTION_RAUCH                     7
#define LOKOMOTVIE_CS2_FUNKTION_RANGIERGANG               8
#define LOKOMOTVIE_CS2_FUNKTION_TELXKUPPLUNG_BEIDSEITIG   9
#define LOKOMOTVIE_CS2_FUNKTION_HORN                     10
#define LOKOMOTVIE_CS2_FUNKTION_SCHAFFNERPFIFF           11
#define LOKOMOTVIE_CS2_FUNKTION_PFEIFE                   12
#define LOKOMOTVIE_CS2_FUNKTION_GLOCKE                   13
#define LOKOMOTVIE_CS2_FUNKTION_HEBEN_SENKEN             15
#define LOKOMOTVIE_CS2_FUNKTION_DREHEN_LINKS             16
#define LOKOMOTVIE_CS2_FUNKTION_ABV                      18
#define LOKOMOTVIE_CS2_FUNKTION_PUMPE                    19
#define LOKOMOTVIE_CS2_FUNKTION_BREMSENQUITSCHEN         20
#define LOKOMOTVIE_CS2_FUNKTION_SCHALTSTUFEN             22
#define LOKOMOTVIE_CS2_FUNKTION_BETRIEBSGERAEUSCH        23
#define LOKOMOTVIE_CS2_FUNKTION_KOHLE_SCHAUFELN          26
#define LOKOMOTVIE_CS2_FUNKTION_TUERE_OEFFNEN            28
#define LOKOMOTVIE_CS2_FUNKTION_LUEFTER                  29
#define LOKOMOTVIE_CS2_FUNKTION_LUEFTER                  30
#define LOKOMOTVIE_CS2_FUNKTION_FEUERBUECHSE             31
#define LOKOMOTVIE_CS2_FUNKTION_INNENBELEUCHTUNG         32
#define LOKOMOTVIE_CS2_FUNKTION_SCHUETTELROST            36
#define LOKOMOTVIE_CS2_FUNKTION_SCHIENENSTOSS            37
#define LOKOMOTVIE_CS2_FUNKTION_ZUGLAUFSCHILD            40
#define LOKOMOTVIE_CS2_FUNKTION_FUEHRERSTAND_HINTEN      41
#define LOKOMOTVIE_CS2_FUNKTION_FUEHRERSTAND_VORN        42
#define LOKOMOTVIE_CS2_FUNKTION_KUPPELN                  43
#define LOKOMOTVIE_CS2_FUNKTION_PUFFERSTOSS              44
#define LOKOMOTVIE_CS2_FUNKTION_BLINKLICHT               47
#define LOKOMOTVIE_CS2_FUNKTION_FUEHRERSTANDSBEL         48
#define LOKOMOTVIE_CS2_FUNKTION_PRESSLUFT                49
#define LOKOMOTVIE_CS2_FUNKTION_F1                       51
#define LOKOMOTVIE_CS2_FUNKTION_F2                       52
#define LOKOMOTVIE_CS2_FUNKTION_F3                       53
#define LOKOMOTVIE_CS2_FUNKTION_F4                       54
#define LOKOMOTVIE_CS2_FUNKTION_F5                       55
#define LOKOMOTVIE_CS2_FUNKTION_F6                       56
#define LOKOMOTVIE_CS2_FUNKTION_F7                       57
#define LOKOMOTVIE_CS2_FUNKTION_F8                       58
#define LOKOMOTVIE_CS2_FUNKTION_F9                       59
#define LOKOMOTVIE_CS2_FUNKTION_F10                      60
#define LOKOMOTVIE_CS2_FUNKTION_F11                      61
#define LOKOMOTVIE_CS2_FUNKTION_F12                      62
#define LOKOMOTVIE_CS2_FUNKTION_F13                      63
#define LOKOMOTVIE_CS2_FUNKTION_F14                      64
#define LOKOMOTVIE_CS2_FUNKTION_F15                      65
#define LOKOMOTVIE_CS2_FUNKTION_F16                      66
#define LOKOMOTVIE_CS2_FUNKTION_F17                      67
#define LOKOMOTVIE_CS2_FUNKTION_F18                      68
#define LOKOMOTVIE_CS2_FUNKTION_F19                      69
#define LOKOMOTVIE_CS2_FUNKTION_F20                      70
#define LOKOMOTVIE_CS2_FUNKTION_F21                      71
#define LOKOMOTVIE_CS2_FUNKTION_F22                      72
#define LOKOMOTVIE_CS2_FUNKTION_F23                      73
#define LOKOMOTVIE_CS2_FUNKTION_F24                      74
#define LOKOMOTVIE_CS2_FUNKTION_F25                      75
#define LOKOMOTVIE_CS2_FUNKTION_F26                      76
#define LOKOMOTVIE_CS2_FUNKTION_F27                      77
#define LOKOMOTVIE_CS2_FUNKTION_F28                      78
#define LOKOMOTVIE_CS2_FUNKTION_F29                      79
#define LOKOMOTVIE_CS2_FUNKTION_F30                      80
#define LOKOMOTVIE_CS2_FUNKTION_F31                      81
#define LOKOMOTVIE_CS2_FUNKTION_TELEXKUPPLUNG_HINTEN     82
#define LOKOMOTVIE_CS2_FUNKTION_LUEFTER                  89
#define LOKOMOTVIE_CS2_FUNKTION_TRIEBWERKSBELEUCHTUNG    90
#define LOKOMOTVIE_CS2_FUNKTION_ZYLINDER_AUSBLASEN       91
#define LOKOMOTVIE_CS2_FUNKTION_92                       92 /* Symbol nicht gefunden */
#define LOKOMOTVIE_CS2_FUNKTION_101                     101 /* kein Icon */
#define LOKOMOTVIE_CS2_FUNKTION_106                     106 /* kein Icon */
#define LOKOMOTVIE_CS2_FUNKTION_108                     108 /* kein Icon */
#define LOKOMOTVIE_CS2_FUNKTION_111                     111 /* kein Icon */
#define LOKOMOTVIE_CS2_FUNKTION_112                     112 /* kein Icon */
#define LOKOMOTVIE_CS2_FUNKTION_GERAEUSCH               133
#define LOKOMOTVIE_CS2_FUNKTION_HORN                    138
#define LOKOMOTVIE_CS2_FUNKTION_SCHAFFNERPFIFF          139
#define LOKOMOTVIE_CS2_FUNKTION_PFEIFE                  140
#define LOKOMOTVIE_CS2_FUNKTION_GLOCKE                  141
#define LOKOMOTVIE_CS2_FUNKTION_1BREMSEN_QUIETSCHEN     148
#define LOKOMOTVIE_CS2_FUNKTION_SCHALTSTUFEN            149
#define LOKOMOTVIE_CS2_FUNKTION_BAHNHOFSANSAGE          153
#define LOKOMOTVIE_CS2_FUNKTION_TUERE_OEFFNEN           156
#define LOKOMOTVIE_CS2_FUNKTION_SCHUETTELROST           164
#define LOKOMOTVIE_CS2_FUNKTION_KUPPELN                 171
#define LOKOMOTVIE_CS2_FUNKTION_PUFFERSTOSS             172
#define LOKOMOTVIE_CS2_FUNKTION_ZUGANSAGE               173
#define LOKOMOTVIE_CS2_FUNKTION_PRESSLUFT               177
#define LOKOMOTVIE_CS2_FUNKTION_ZYLINDER_AUSBLASEN      219
#define LOKOMOTVIE_CS2_FUNKTION_220                     220 /* Symbol nicht gefunden */
#define LOKOMOTVIE_CS2_FUNKTION_236                     236 /* kein Icon */


#endif
